"""empty message

Revision ID: 336d93e24139
Revises: 55f5c8169ed6
Create Date: 2025-08-26 20:25:40.446631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336d93e24139'
down_revision = '55f5c8169ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_memos_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_memos_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
